#include <cstddef>
#include <print>

/**
 *   Euler Project: Even Fibonacci Numbers
 *   Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
 * 8, 13, 21, 34, 55, 89, By considering the terms in the Fibonacci sequence
 * whose values do not exceed four million, find the sum of the even-valued
 * terms.
 */

#define MAX_LIMIT 4'000'000

size_t even_fib(size_t num) {
  size_t sum = 0;
  size_t curr_fib = 1;
  size_t prev_fib = 1;

  for (size_t i = 0; i < num; i++)

  {
    size_t tmp = prev_fib;
    prev_fib = curr_fib;
    curr_fib += tmp;
    if (curr_fib % 2 == 0 && curr_fib <= MAX_LIMIT)
      sum += curr_fib;

    if (sum >= MAX_LIMIT)
      break;
  }

  return sum;
}

int main() {
  std::println("Hello World");
  std::println("Fib at {} is {}", MAX_LIMIT, even_fib(MAX_LIMIT));
  return 0;
}
